@host = http://localhost:3000

GET {{host}}/api/all

###
POST {{host}}/api/new
Content-Type: application/json

{
    "name": "Sonia",
    "surname": "Amenábar",
    "age": 34,
    "tratement": 92
}

###
DELETE {{host}}/api/1