@host = http://localhost:3000

GET {{host}}/api/all

###
POST {{host}}/api/new
Content-Type: application/json

{
    "nombre": "Lorenzo",
    "apellidos": "López Rodríguez",
    "edad": 29,
    "tratamiento": 60
}

###
DELETE {{host}}/api/1